version: 2

sources:
  - name: northwind
    schema: main

    tables:
      - name: Order
      - name: Customer
      - name: OrderDetail
      - name: Product
      - name: Category
      - name: Supplier